'use client'

import {useState,useTransition} from 'react'
import {useRouter} from 'next/navigation'
import {teamAction} from '@/app/actions/team-workflow'
import {updateDeliverableType} from '@/app/actions/deliverables'
import {DateTime,localDateTime} from '@/components/shared/date-time'
import {toInstant,validInterval} from '@/lib/workflow/team'
import {StatusBadge} from '@/components/ui/badges'

type Props={entity:'CAMPAIGN'|'DELIVERABLE'|'TASK';id:string;startAt:string|null;endAt:string|null;state:string;canManage:boolean;type?:string;status:string}

export function Governance({entity,id,startAt,endAt,state,canManage,type,status}:Props){
 const router=useRouter(),[message,setMessage]=useState(''),[scheduleEditing,setScheduleEditing]=useState(false),[typeEditing,setTypeEditing]=useState(false),[pending,start]=useTransition()
 function run(fn:()=>Promise<{success:boolean;error?:string}>,done?:()=>void){start(async()=>{try{const r=await fn();setMessage(r.success?'Saved.':r.error??'Unable to save.');if(r.success){done?.();router.refresh()}}catch(e){setMessage(e instanceof Error?e.message:'Invalid input.')}})}
 const editable=canManage&&!['DROPPED','COMPLETED','APPROVED'].includes(status)
 const saveSchedule=(fd:FormData)=>run(()=>{const a=String(fd.get('start')),b=String(fd.get('end'));if(!validInterval(a,b))throw new Error('End cannot precede Start.');return teamAction('schedule',{p_entity:entity,p_id:id,p_start_at:toInstant(a),p_end_at:toInstant(b)})},()=>setScheduleEditing(false))
 const toggleState=()=>run(()=>teamAction('operationalState',{p_entity:entity,p_id:id,p_state:state==='ON_HOLD'?'ACTIVE':'ON_HOLD'}))

 if(entity==='DELIVERABLE')return <section className="task-overview governance governance--deliverable"><div className="governance__header"><div><span className="eyebrow">Operations</span><h2>Schedule & status</h2></div></div>{message&&<p className="action-feedback" role="status">{message}</p>}
  <div className="deliverable-governance__grid">
   <section className="deliverable-governance__panel"><header><div><small>Timeline</small><h3>Schedule</h3></div>{editable&&!scheduleEditing&&<button type="button" className="button button--compact" onClick={()=>setScheduleEditing(true)}>Edit schedule</button>}</header>{scheduleEditing?<form className="deliverable-schedule-editor" action={saveSchedule}><label>Start<input name="start" type="datetime-local" defaultValue={localDateTime(startAt)}/></label><label>End<input name="end" type="datetime-local" defaultValue={localDateTime(endAt)}/></label><footer><button type="button" className="button" disabled={pending} onClick={()=>setScheduleEditing(false)}>Cancel</button><button className="button button--primary" disabled={pending}>Save schedule</button></footer></form>:<dl><div><dt>Start date</dt><dd><DateTime value={startAt}/></dd></div><div><dt>Target date</dt><dd><DateTime value={endAt}/></dd></div></dl>}</section>
   <section className="deliverable-governance__panel"><header><div><small>Workflow availability</small><h3>Operational state</h3></div><StatusBadge status={state==='ON_HOLD'?'ON_HOLD':'ACTIVE'}/></header><div className="deliverable-state-copy"><strong>{state==='ON_HOLD'?'Work is on hold':'Production is active'}</strong><p>Operational holds never bypass approval or review gates.</p></div>{editable&&<button type="button" className="button" disabled={pending} onClick={toggleState}>{state==='ON_HOLD'?'Resume production':'Put on hold'}</button>}</section>
  </div>
  <div className="deliverable-governance__footer"><div className="deliverable-type-control"><div><small>Deliverable type</small><strong>{type??'Not set'}</strong></div>{editable&&!typeEditing&&<button type="button" className="button" onClick={()=>setTypeEditing(true)}>Change type</button>}{typeEditing&&<form action={fd=>run(()=>updateDeliverableType(id,String(fd.get('type'))),()=>setTypeEditing(false))}><select name="type" defaultValue={type}>{['Static Poster','Instagram Carousel','Instagram Reel','Presentation'].map(t=><option key={t}>{t}</option>)}</select><button type="button" className="button" disabled={pending} onClick={()=>setTypeEditing(false)}>Cancel</button><button className="button button--primary" disabled={pending}>Save type</button></form>}</div>{editable&&<div className="deliverable-danger-action"><div><strong>Drop Deliverable</strong><small>Stops further workflow while preserving history.</small></div><button type="button" className="button button--danger" disabled={pending} onClick={()=>{const reason=window.prompt('Drop this Deliverable? History remains, but further workflow stops. Enter a reason.');if(reason&&window.confirm('Confirm dropping this Deliverable?'))run(()=>teamAction('dropDeliverable',{p_deliverable_id:id,p_reason:reason}))}}>Drop Deliverable</button></div>}</div>
 </section>

 return <section className={`task-overview governance governance--${entity.toLowerCase()}`}><div className="governance__header"><div><span className="eyebrow">Operations</span><h2>Schedule & status</h2></div><StatusBadge status={state==='ON_HOLD'?'ON_HOLD':status}/></div><div className="governance__facts"><div><span>Start</span><strong><DateTime value={startAt}/></strong></div><div><span>End</span><strong><DateTime value={endAt}/></strong></div></div>{message&&<p className="action-feedback" role="status">{message}</p>}
  {editable&&<div className="governance__controls"><div className="governance__hold"><div><strong>{state==='ON_HOLD'?'Work is on hold':'Production is active'}</strong><span>Operational holds never bypass approval or review gates.</span></div><button type="button" className="button" disabled={pending} onClick={toggleState}>{state==='ON_HOLD'?'Resume':'Put on hold'}</button></div>{entity!=='TASK'&&(scheduleEditing?<form className="governance__schedule" action={saveSchedule}><label>Start<input name="start" type="datetime-local" defaultValue={localDateTime(startAt)}/></label><label>End<input name="end" type="datetime-local" defaultValue={localDateTime(endAt)}/></label><div className="governance__schedule-actions"><button type="button" className="button" disabled={pending} onClick={()=>setScheduleEditing(false)}>Cancel</button><button className="button button--primary" disabled={pending}>Save</button></div></form>:<button type="button" className="button governance__edit-schedule" onClick={()=>setScheduleEditing(true)}>Edit schedule</button>)}</div>}
 </section>
}
