'use client'
import Link from 'next/link'
import type {Campaign,HierarchyData} from '@/lib/hierarchy/data'
import {CommonFilters,useCommonFilters} from '@/components/shared/common-filters'
import {DateTime} from '@/components/shared/date-time'
import {StatusBadge} from '@/components/ui/badges'
import {ProgressBar} from '@/components/shared/states'
import {projectKind,isOverdue,isProjectAtRisk} from '@/lib/workflow/team'

export function CampaignExplorer({campaigns,data}:{campaigns:Campaign[];data:HierarchyData}){
 const f=useCommonFilters(),opts=(values:string[])=>[...new Set(values)].map(value=>({value,label:value}))
 const rows=campaigns.filter(c=>(c.name+' '+c.clientName).toLowerCase().includes(f.get('q').toLowerCase())&&(!f.get('status')||c.status===f.get('status'))&&(!f.get('client')||c.client_id===f.get('client'))&&(!f.get('priority')||c.priority===f.get('priority'))&&(!f.get('projectType')||projectKind(data.deliverables.filter(d=>d.campaign_id===c.id).length)===f.get('projectType'))&&(!f.get('overdue')||isOverdue(c.end_at,c.status!=='ACTIVE'))&&(!f.get('risk')||isProjectAtRisk(c.id,data))&&(!f.get('poc')||data.campaignPocs.some(p=>p.campaign_id===c.id&&p.client_poc_id===f.get('poc'))))
 return <><CommonFilters results={rows.length} fields={[{key:'q',label:'Search Projects'},{key:'risk',label:'Risk',options:[{value:'1',label:'At risk'}]},{key:'client',label:'Client',options:[...new Map(campaigns.map(c=>[c.client_id,{value:c.client_id,label:c.clientName}])).values()]},{key:'status',label:'Status',options:opts(['ACTIVE','COMPLETED','ARCHIVED'])},{key:'priority',label:'Priority',options:opts(['Low','Medium','High'])},{key:'projectType',label:'Type',options:opts(['Project','Campaign'])},{key:'poc',label:'POC',options:data.pocs.map(p=>({value:p.id,label:p.name}))},{key:'overdue',label:'Schedule',options:[{value:'1',label:'Overdue'}]}]}/>
 <div className="project-table-wrap"><table className="project-table"><thead><tr><th>Project</th><th>Client</th><th>Status</th><th>Delivery</th><th>Progress</th><th>Timeline</th><th><span className="sr-only">Open</span></th></tr></thead><tbody>{rows.map(c=>{const ds=data.deliverables.filter(d=>d.campaign_id===c.id),included=ds.filter(d=>d.status!=='DROPPED'),progress=included.length?Math.round(included.filter(d=>d.status==='COMPLETED').length/included.length*100):0,risk=isProjectAtRisk(c.id,data),currentStages=data.stages.filter(s=>included.some(d=>d.id===s.deliverable_id)&&['ACTIVE','CLIENT_DECISION'].includes(s.status));return <tr key={c.id}><td><Link className="project-cell" href={'/campaigns/'+c.id}><span className="project-cell__icon">{c.name.slice(0,1).toUpperCase()}</span><span><strong>{c.name}</strong><small>{projectKind(ds.length)} · {c.priority??'Standard'} priority{risk?' · At risk':''}</small></span></Link></td><td data-label="Client"><strong className="table-client">{c.clientName}</strong></td><td data-label="Status"><StatusBadge status={c.status}/></td><td data-label="Delivery"><strong className="table-value">{ds.length} deliverable{ds.length===1?'':'s'}</strong><small className="table-subvalue">{currentStages[0]?.name??(c.status==='COMPLETED'?'Complete':'Not started')}</small></td><td data-label="Progress"><div className="table-progress"><ProgressBar value={progress}/></div></td><td data-label="Timeline"><div className={isOverdue(c.end_at,c.status!=='ACTIVE')?'table-date is-overdue':'table-date'}><DateTime value={c.end_at}/><small>{isOverdue(c.end_at,c.status!=='ACTIVE')?'Overdue':'Target date'}</small></div></td><td><Link className="row-arrow" href={'/campaigns/'+c.id} aria-label={`Open ${c.name}`}>→</Link></td></tr>})}</tbody></table>{!rows.length&&<div className="content-empty"><span>◇</span><h2>No Projects found</h2><p>Try adjusting or clearing the active filters.</p></div>}</div></>
}
