import{createClient}from'@/lib/supabase/server'
export type Campaign={start_at:string|null;end_at:string|null;operational_status:string;id:string;name:string;status:string;priority:string|null;deadline:string|null;client_id:string;clientName:string}
export type Deliverable={start_at:string|null;end_at:string|null;operational_status:string;id:string;campaign_id:string;name:string;type:string;status:string;client_revision:number}
export type Stage={id:string;deliverable_id:string;name:string;dept:string;status:string;stage_order:number;rework_pending:boolean}
export type HierarchyTask={start_at:string|null;end_at:string|null;operational_status:string;reviewer_id:string|null;priority:string;task_type:string;id:string;stage_id:string;status:string;title:string;description:string;deadline:string|null;assignee_id:string|null;task_order:number;is_client_change:boolean;client_revision:number|null;iteration:number|null}
export type HierarchyActivity={id:string;entity_type:string;entity_id:string;action:string;created_at:string;actorName:string}
export type ClientDecision={id:string;deliverable_id:string;stage_id:string;client_poc_id:string|null;decision:string;client_revision:number;channel:string|null;contact_person:string|null;feedback:string|null;notes:string|null;recorded_at:string}
export type HierarchyUser={id:string;name:string;role:string|null;dept:string|null;status:string}
export type SubmissionOption={id:string;submission_id:string;name:string;link:string;note:string|null;decision:string}
export type Submission={id:string;task_id:string;note:string|null;manager_feedback:string|null;decision_type:string|null;submitted_at:string;options:SubmissionOption[]}
export type HierarchyPoc={id:string;client_id:string;name:string;designation:string|null;email:string|null;phone:string|null;whatsapp:string|null;is_primary:boolean;status:string}
export type CampaignPoc={id:string;campaign_id:string;client_poc_id:string;is_primary:boolean}
export type CampaignDocumentFile={id:string;document_id:string;file_name:string;file_url:string}
export type CampaignDocument={id:string;campaign_id:string;document_type:'IDEATION'|'BRIEF';title:string;content:string;created_at:string;updated_at:string;files:CampaignDocumentFile[]}
export type Rework={id:string;deliverable_id:string;source_stage_id:string;target_stage_id:string;client_revision:number;department:string;status:string;assigned_at:string;completed_at:string|null}
export type ChangeRequest={id:string;deliverable_id:string;target_stage_id:string;client_revision:number;client_poc_id:string|null;feedback:string;status:string;created_at:string}
export type ChangeLink={id:string;change_request_id:string;task_id:string;stage_id:string}
export type Regularization={id:string;task_id:string;user_id:string;actual_start_at:string;actual_end_at:string;reason:string;status:string;requested_at:string;reviewed_by:string|null;reviewed_at:string|null;manager_comment:string|null}
export type HierarchyData={changeRequests:ChangeRequest[];changeLinks:ChangeLink[];regularizations:Regularization[];campaigns:Campaign[];deliverables:Deliverable[];stages:Stage[];tasks:HierarchyTask[];activity:HierarchyActivity[];decisions:ClientDecision[];users:HierarchyUser[];submissions:Submission[];pocs:HierarchyPoc[];campaignPocs:CampaignPoc[];documents:CampaignDocument[];reworks:Rework[];partial:boolean}
export async function loadHierarchy():Promise<HierarchyData>{const db=await createClient();const[c,d,s,t,a,cd,u,sub,opt,pocs,cp,docs,files,rw,cr,cl,reg]=await Promise.all([
 db.from('pmt_campaigns').select('id,name,status,priority,deadline,start_at,end_at,operational_status,client_id,pmt_clients(name)').order('end_at'),
 db.from('pmt_deliverables').select('id,campaign_id,name,type,status,client_revision,start_at,end_at,operational_status'),db.from('pmt_stages').select('id,deliverable_id,name,dept,status,stage_order,rework_pending').order('stage_order'),
 db.from('pmt_tasks').select('id,stage_id,status,title,description,deadline,assignee_id,task_order,is_client_change,client_revision,iteration,start_at,end_at,operational_status,reviewer_id,priority,task_type'),db.from('pmt_activity').select('id,entity_type,entity_id,action,created_at,pmt_users(name)').order('created_at',{ascending:false}).limit(150),
 db.from('pmt_client_decisions').select('id,deliverable_id,stage_id,client_poc_id,decision,client_revision,channel,contact_person,feedback,notes,recorded_at').order('recorded_at',{ascending:false}),db.from('pmt_users').select('id,name,role,dept,status'),
 db.from('pmt_submissions').select('id,task_id,note,manager_feedback,decision_type,submitted_at').order('submitted_at',{ascending:false}),db.from('pmt_submission_options').select('id,submission_id,name,link,note,decision'),
 db.from('pmt_client_pocs').select('id,client_id,name,designation,email,phone,whatsapp,is_primary,status'),db.from('pmt_campaign_pocs').select('id,campaign_id,client_poc_id,is_primary'),
 db.from('pmt_campaign_documents').select('id,campaign_id,document_type,title,content,created_at,updated_at'),db.from('pmt_campaign_document_files').select('id,document_id,file_name,file_url'),
 db.from('pmt_reworks').select('id,deliverable_id,source_stage_id,target_stage_id,client_revision,department,status,assigned_at,completed_at'),db.from('pmt_change_requests').select('*').order('created_at'),db.from('pmt_change_request_tasks').select('*'),db.from('pmt_task_regularizations').select('*').order('requested_at',{ascending:false})]);
 const campaigns=(c.data??[]).map(row=>{const x=row as unknown as Omit<Campaign,'clientName'>&{pmt_clients:{name:string}|null};return{...x,clientName:x.pmt_clients?.name??'Client unavailable'}});const activity=(a.data??[]).map(row=>{const x=row as unknown as Omit<HierarchyActivity,'actorName'>&{pmt_users:{name:string}|null};return{...x,actorName:x.pmt_users?.name??'PMT'}});const options=(opt.data??[])as SubmissionOption[];const submissions=((sub.data??[])as Omit<Submission,'options'>[]).map(x=>({...x,options:options.filter(o=>o.submission_id===x.id)}));const fileRows=(files.data??[])as CampaignDocumentFile[];const documents=((docs.data??[])as Omit<CampaignDocument,'files'>[]).map(x=>({...x,files:fileRows.filter(f=>f.document_id===x.id)}));const all=[c,d,s,t,a,cd,u,sub,opt,pocs,cp,docs,files,rw,cr,cl,reg];return{changeRequests:(cr.data??[])as ChangeRequest[],changeLinks:(cl.data??[])as ChangeLink[],regularizations:(reg.data??[])as Regularization[],campaigns,deliverables:(d.data??[])as Deliverable[],stages:(s.data??[])as Stage[],tasks:(t.data??[])as HierarchyTask[],activity,decisions:(cd.data??[])as ClientDecision[],users:(u.data??[])as HierarchyUser[],submissions,pocs:(pocs.data??[])as HierarchyPoc[],campaignPocs:(cp.data??[])as CampaignPoc[],documents,reworks:(rw.data??[])as Rework[],partial:all.some(x=>!!x.error)}}
export const campaignProgress=(id:string,d:HierarchyData)=>{const rows=d.deliverables.filter(x=>x.campaign_id===id&&x.status!=='DROPPED');return rows.length?Math.round(rows.filter(x=>x.status==='COMPLETED').length/rows.length*100):0}
export const deliverableProgress=(id:string,d:HierarchyData)=>{const rows=d.stages.filter(x=>x.deliverable_id===id);return rows.length?Math.round(rows.filter(x=>x.status==='COMPLETED').length/rows.length*100):0}
export const stageProgress=(id:string,d:HierarchyData)=>{const rows=d.tasks.filter(x=>x.stage_id===id);return rows.length?Math.round(rows.filter(x=>x.status==='APPROVED').length/rows.length*100):0}
export const isEligibleReworkTarget=(stage:Stage,data:HierarchyData)=>stage.status==='COMPLETED'||stage.status==='CLIENT_DECISION'||data.tasks.some(t=>t.stage_id===stage.id&&(['IN_REVIEW','CHANGES_REQUIRED','APPROVED'].includes(t.status)||data.submissions.some(s=>s.task_id===t.id)))
