'use client'
import {useState,useTransition} from 'react'
import {useRouter} from 'next/navigation'
import type {ClientRecord,ClientPoc} from '@/lib/clients/data'
import {teamAction} from '@/app/actions/team-workflow'
import {toInstant,validInterval} from '@/lib/workflow/team'
const types=['Static Poster','Instagram Carousel','Instagram Reel','Presentation']
type Doc={title:string;content:string;files:{file_name:string;file_url:string}[]}
export function NewProject({clients,pocs}:{clients:ClientRecord[];pocs:ClientPoc[]}){
 const router=useRouter(),[open,setOpen]=useState(false),[step,setStep]=useState(0),[client,setClient]=useState(''),[selected,setSelected]=useState<string[]>([]),[primary,setPrimary]=useState(''),[pending,start]=useTransition(),[message,setMessage]=useState('');
 const [name,setName]=useState(''),[priority,setPriority]=useState('Medium'),[begin,setBegin]=useState(''),[end,setEnd]=useState('');
 const [docs,setDocs]=useState<Doc[]>([{title:'Ideation',content:'',files:[]},{title:'Brief',content:'',files:[]}]);
 const [deliverables,setDeliverables]=useState([{name:'',type:types[0],start_at:'',end_at:''}]);
 const available=pocs.filter(p=>p.client_id===client&&p.status==='ACTIVE');
 function next(){setMessage('');if(step===0&&(!name.trim()||!client||!selected.length||!primary||!validInterval(begin,end))){setMessage('Name, Client, one active primary POC, and a valid schedule are required.');return}
 if((step===1||step===2)&&(!docs[step-1].title.trim()||(!docs[step-1].content.trim()&&!docs[step-1].files.length)||docs[step-1].files.some(f=>!f.file_name.trim()||!f.file_url.trim()))){setMessage('Provide a title and content or complete file links.');return}setStep(s=>s+1)}
 function submit(){start(async()=>{try{if(deliverables.some(d=>!d.name.trim()||!validInterval(d.start_at,d.end_at)))throw new Error('Every Deliverable needs a name and valid date/time interval.');
 const r=await teamAction('createProject',{p_client_id:client,p_name:name,p_priority:priority,p_start_at:toInstant(begin),p_end_at:toInstant(end),p_poc_ids:selected,p_primary_poc_id:primary,p_ideation:docs[0],p_brief:docs[1],p_deliverables:deliverables.map(d=>({...d,start_at:toInstant(d.start_at),end_at:toInstant(d.end_at)}))});
 if(!r.success){setMessage(r.error);return}setOpen(false);router.push('/campaigns/'+r.data);router.refresh()}catch(e){setMessage(e instanceof Error?e.message:'Unable to create Project.')}})}
 return <><div className="page-primary-actions"><button className="button button--primary" onClick={()=>setOpen(true)}>+ New Project</button></div>{open&&<div className="drawer-scrim"><aside className="task-drawer campaign-drawer" role="dialog" aria-modal="true" aria-label="New Project"><header><h2>New Project · {['Information','Ideation','Brief','Deliverables'][step]}</h2><button disabled={pending} onClick={()=>setOpen(false)}>×</button></header><form onSubmit={e=>{e.preventDefault();step<3?next():submit()}}>
 {message&&<p role="alert" className="action-feedback">{message}</p>}
 {step===0&&<><label>Project name *<input required value={name} onChange={e=>setName(e.target.value)}/></label><label>Client *<select required value={client} onChange={e=>{setClient(e.target.value);setSelected([]);setPrimary('')}}><option value="">Choose Client</option>{clients.filter(c=>c.status==='ACTIVE').map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><fieldset><legend>Project POCs *</legend>{client&&!available.length&&<p>Add an active POC on Client Detail before creating a Project.</p>}{available.map(p=><div className="check-row" key={p.id}><label><input type="checkbox" checked={selected.includes(p.id)} onChange={e=>{if(e.target.checked){setSelected(s=>[...s,p.id]);if(!primary)setPrimary(p.id)}else{setSelected(s=>s.filter(id=>id!==p.id));if(primary===p.id)setPrimary(selected.find(id=>id!==p.id)??'')}}}/>{p.name}</label>{selected.includes(p.id)&&<label><input type="radio" checked={primary===p.id} onChange={()=>setPrimary(p.id)}/>Primary</label>}</div>)}</fieldset><label>Priority<select value={priority} onChange={e=>setPriority(e.target.value)}>{['Low','Medium','High'].map(p=><option key={p}>{p}</option>)}</select></label><label>Start<input type="datetime-local" value={begin} onChange={e=>setBegin(e.target.value)}/></label><label>End<input type="datetime-local" min={begin} value={end} onChange={e=>setEnd(e.target.value)}/></label></>}
 {(step===1||step===2)&&<><label>Title *<input required value={docs[step-1].title} onChange={e=>setDocs(ds=>ds.map((d,i)=>i===step-1?{...d,title:e.target.value}:d))}/></label><label>Content<textarea rows={6} value={docs[step-1].content} onChange={e=>setDocs(ds=>ds.map((d,i)=>i===step-1?{...d,content:e.target.value}:d))}/></label>{docs[step-1].files.map((f,j)=><fieldset key={j}><label>File name<input required value={f.file_name} onChange={e=>setDocs(ds=>ds.map((d,i)=>i===step-1?{...d,files:d.files.map((x,k)=>k===j?{...x,file_name:e.target.value}:x)}:d))}/></label><label>URL<input required type="url" value={f.file_url} onChange={e=>setDocs(ds=>ds.map((d,i)=>i===step-1?{...d,files:d.files.map((x,k)=>k===j?{...x,file_url:e.target.value}:x)}:d))}/></label><button type="button" onClick={()=>setDocs(ds=>ds.map((d,i)=>i===step-1?{...d,files:d.files.filter((_,k)=>k!==j)}:d))}>Remove</button></fieldset>)}<button className="button" type="button" onClick={()=>setDocs(ds=>ds.map((d,i)=>i===step-1?{...d,files:[...d.files,{file_name:'',file_url:''}]}:d))}>+ File link</button></>}
 {step===3&&<>{deliverables.map((d,i)=><fieldset key={i}><legend>Deliverable {i+1}</legend>{(['name','start_at','end_at'] as const).map(k=><label key={k}>{k==='name'?'Name *':k==='start_at'?'Start':'End'}<input required={k==='name'} type={k==='name'?'text':'datetime-local'} value={d[k]} onChange={e=>setDeliverables(ds=>ds.map((x,j)=>i===j?{...x,[k]:e.target.value}:x))}/></label>)}<label>Type<select value={d.type} onChange={e=>setDeliverables(ds=>ds.map((x,j)=>j===i?{...x,type:e.target.value}:x))}>{types.map(t=><option key={t}>{t}</option>)}</select></label>{deliverables.length>1&&<button type="button" onClick={()=>setDeliverables(ds=>ds.filter((_,j)=>i!==j))}>Remove</button>}</fieldset>)}<button type="button" className="button" onClick={()=>setDeliverables(ds=>[...ds,{name:'',type:types[0],start_at:'',end_at:''}])}>+ Deliverable</button></>}
 <footer>{step>0&&<button type="button" className="button" disabled={pending} onClick={()=>setStep(s=>s-1)}>Back</button>}<button className="button button--primary" disabled={pending}>{pending?'Creating…':step===3?'Create Project':'Next'}</button></footer>
 </form></aside></div>}</>
}
