'use client'

import {useState,useTransition} from 'react'
import {useRouter} from 'next/navigation'
import type {ClientPoc} from '@/lib/clients/data'
import {createClientPoc,deactivateClientPoc,updateClientPoc,type PocInput} from '@/app/actions/clients'
import {StatusBadge} from '@/components/ui/badges'
import {EmptyState} from '@/components/shared/states'

const blank:PocInput={name:'',designation:'',email:'',phone:'',whatsapp:'',is_primary:false,status:'ACTIVE',notes:''}
const initials=(name:string)=>name.split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase()

export function ClientPocManager({clientId,pocs}:{clientId:string;pocs:ClientPoc[]}){
 const router=useRouter(),[editing,setEditing]=useState<ClientPoc|null|undefined>(undefined),[message,setMessage]=useState<string|null>(null),[pending,start]=useTransition()
 function submit(fd:FormData){const input:PocInput={name:String(fd.get('name')).trim(),designation:String(fd.get('designation')).trim(),email:String(fd.get('email')).trim(),phone:String(fd.get('phone')).trim(),whatsapp:String(fd.get('whatsapp')).trim(),is_primary:fd.get('primary')==='on',status:String(fd.get('status'))as PocInput['status'],notes:String(fd.get('notes')).trim()};start(async()=>{const r=editing?await updateClientPoc(editing.id,input):await createClientPoc(clientId,input);setMessage(r.success?`POC ${editing?'updated':'created'} successfully.`:r.error);if(r.success){setEditing(undefined);router.refresh()}})}
 function deactivate(p:ClientPoc){if(!window.confirm(`Deactivate ${p.name}? An active replacement will become Primary where needed. Projects must retain an active Primary POC.`))return;start(async()=>{const r=await deactivateClientPoc(p.id);setMessage(r.success?'POC deactivated.':r.error);if(r.success)router.refresh()})}
 const initial=editing??blank
 return <section className="hierarchy-primary client-pocs"><div className="section-heading"><div><span className="eyebrow">Client contacts</span><h2>Points of Contact</h2></div><button className="button button--primary" onClick={()=>setEditing(null)}>+ Add POC</button></div>{message&&<div className="action-feedback">{message}</div>}{pocs.length?<div className="poc-list">{pocs.map(p=><article key={p.id}><header><div className="poc-identity"><span className="avatar poc-avatar">{initials(p.name)}</span><div><strong>{p.name}</strong><small>{p.designation??'Designation unavailable'}</small><div className="poc-badges">{p.is_primary&&<b>Primary</b>}<StatusBadge status={p.status}/></div></div></div></header><dl><div><dt>Email</dt><dd>{p.email??'—'}</dd></div><div><dt>Phone</dt><dd>{p.phone??'—'}</dd></div><div><dt>WhatsApp</dt><dd>{p.whatsapp??'—'}</dd></div></dl><footer><button className="button" onClick={()=>setEditing(p)}>Edit contact</button>{p.status==='ACTIVE'&&<button className="button button--danger" onClick={()=>deactivate(p)}>Deactivate</button>}</footer></article>)}</div>:<EmptyState title="No Client POCs yet." description="Add the contacts who can approve Project work."/>}{editing!==undefined&&<div className="drawer-scrim" onMouseDown={()=>setEditing(undefined)}><aside className="task-drawer" role="dialog" aria-modal="true" onMouseDown={e=>e.stopPropagation()}><header><div><span className="eyebrow">Client POC</span><h2>{editing?'Edit POC':'Add POC'}</h2></div><button onClick={()=>setEditing(undefined)}>×</button></header><form action={submit}><label>Name *<input name="name" required defaultValue={initial.name}/></label><label>Designation<input name="designation" defaultValue={initial.designation??''}/></label><label>Email<input name="email" type="email" defaultValue={initial.email??''}/></label><label>Phone<input name="phone" defaultValue={initial.phone??''}/></label><label>WhatsApp<input name="whatsapp" defaultValue={initial.whatsapp??''}/></label><p className="form-hint">Active POCs retain one Primary. Choose another POC to change Primary; deactivation promotes an active replacement where possible.</p><label className="check-row"><input name="primary" type="checkbox" defaultChecked={initial.is_primary}/> Primary POC</label>{editing&&<label>Status<select name="status" defaultValue={initial.status}><option>ACTIVE</option><option>INACTIVE</option></select></label>}{!editing&&<input type="hidden" name="status" value="ACTIVE"/>}<label>Notes<textarea name="notes" rows={3} defaultValue={initial.notes??''}/></label><footer><button type="button" className="button" onClick={()=>setEditing(undefined)}>Cancel</button><button className="button button--primary" disabled={pending}>{pending?'Saving…':'Save POC'}</button></footer></form></aside></div>}</section>
}
