'use client'
import{useEffect,useState}from'react';import Link from'next/link';import{usePathname,useSearchParams}from'next/navigation';import{logout}from'@/app/login/actions';import{createClient}from'@/lib/supabase/client';import type{PmtUser,Role}from'@/lib/auth/types';import{RoleBadge}from'@/components/ui/badges';import{Icon}from'@/components/ui/icon';import{isNavigationItemActive,navigationFor}from'./navigation'
const initials=(name:string)=>name.split(/\s+/).map(p=>p[0]).join('').slice(0,2).toUpperCase()
const present=(value:string)=>value.replace(/\bCampaigns?\b/gi,match=>match.toLowerCase().endsWith('s')?'Projects':'Project')
function routeTitle(path:string){
 const parts=path.split('/').filter(Boolean),root=parts[0]
 if(!root)return'Dashboard'
 const labels:Record<string,string>={dashboard:'Dashboard',campaigns:'Projects',clients:'Clients',work:'Work',activity:'Activity',notifications:'Notifications',users:'Users',profile:'Profile',deliverables:'Deliverable detail',stages:'Stage detail',tasks:'Task detail'}
 if(parts.length>1&&root==='campaigns')return'Project detail'
 if(parts.length>1&&root==='clients')return'Client detail'
 if(parts.length>1&&root==='users')return'User profile'
 return labels[root]??root.replaceAll('-',' ').replace(/\b\w/g,x=>x.toUpperCase())
}
function Sidebar({user,open,onClose}:{user:PmtUser&{role:Role};open:boolean;onClose:()=>void}){const path=usePathname(),search=useSearchParams();return <><button className={`shell-scrim ${open?'is-open':''}`} onClick={onClose} aria-label="Close navigation"/><aside className={`sidebar ${open?'is-open':''}`} aria-label="Primary navigation"><div className="sidebar__brand"><span className="brand-mark"><span>P</span></span><span><strong>PMT</strong><small>Project management</small></span><button className="icon-button sidebar__close" onClick={onClose} aria-label="Close navigation">×</button></div><div className="sidebar__context"><span><small>Workspace</small><strong>Production team</strong></span><Icon name="chevron-down"/></div><nav className="sidebar__nav">{navigationFor(user.role).map(g=><div className="nav-group" key={g.label}><p>{g.label}</p>{g.items.map(i=>{const active=isNavigationItemActive(i,path,search);return <Link className={`nav-link ${active?'is-active':''}`} href={i.href} onClick={onClose} key={`${i.label}-${i.href}`}><span className="nav-link__icon"><Icon name={i.icon}/></span><span>{i.label}</span>{active&&<i className="nav-link__active-dot"/>}</Link>})}</div>)}</nav><div className="sidebar__footer"><div className="avatar">{initials(user.name)}</div><div className="sidebar__user"><strong>{user.name}</strong><small>{user.dept??'All departments'}</small><RoleBadge role={user.role}/></div><form action={logout}><button className="icon-button sidebar__logout" aria-label="Sign out" title="Sign out"><Icon name="logout"/></button></form></div></aside></>}
type Notice={id:string;message:string;read:boolean;created_at:string}
function Topbar({user,onMenu}:{user:PmtUser&{role:Role};onMenu:()=>void}){const path=usePathname(),[notices,setNotices]=useState<Notice[]>([]),[noticeOpen,setNoticeOpen]=useState(false),[profileOpen,setProfileOpen]=useState(false);useEffect(()=>{let live=true;createClient().from('pmt_notifications').select('id,message,read,created_at').eq('user_id',user.id).order('created_at',{ascending:false}).limit(4).then(({data})=>{if(live)setNotices((data??[])as Notice[])});return()=>{live=false}},[user.id]);const unread=notices.filter(x=>!x.read).length,title=routeTitle(path);return <header className="topbar"><button className="icon-button topbar__menu" onClick={onMenu} aria-label="Open navigation"><Icon name="menu"/></button><div className="topbar__context"><strong>{title}</strong><span>PMT workspace</span></div><div className="topbar__actions"><Link className="topbar__search" href="/work"><Icon name="search"/><span>Search workspace</span><kbd>/</kbd></Link><div className="topbar-popover-wrap"><button className="icon-button notification-button" aria-label={`${unread} unread notifications`} aria-expanded={noticeOpen} onClick={()=>{setNoticeOpen(x=>!x);setProfileOpen(false)}}><Icon name="bell"/>{unread>0&&<span className="notification-dot"/>}</button>{noticeOpen&&<div className="topbar-popover notification-popover" role="dialog" aria-label="Recent notifications"><header><strong>Notifications</strong><Link href="/notifications">View all</Link></header>{notices.length?notices.map(x=><div className={x.read?'is-read':''} key={x.id}><span/><p>{present(x.message)}</p></div>):<p className="popover-empty">You’re all caught up.</p>}</div>}</div><span className="topbar__divider"/><div className="topbar-popover-wrap"><button className="topbar__identity" onClick={()=>{setProfileOpen(x=>!x);setNoticeOpen(false)}} aria-expanded={profileOpen} aria-label="Open profile menu"><div className="avatar">{initials(user.name)}</div><span><strong>{user.name}</strong><small>{user.dept??'All departments'}</small></span><Icon name="chevron-down"/></button>{profileOpen&&<div className="topbar-popover profile-popover" role="menu" aria-label="Profile menu"><Link href="/profile">Profile</Link><form action={logout}><button>Sign out</button></form></div>}</div></div></header>}
export function AppShell({user,children}:{user:PmtUser;children:React.ReactNode}){const[open,setOpen]=useState(false);if(!user.role)return null;const active=user as PmtUser&{role:Role};return <div className="app-shell"><Sidebar user={active} open={open} onClose={()=>setOpen(false)}/><div className="app-shell__workspace"><Topbar user={active} onMenu={()=>setOpen(true)}/><main className="app-shell__main">{children}</main></div></div>}
